zowe/zlux-editor

webClient/src/app/editor/project-tree/project-tree.component.ts
webClient/src/app/shared/dialog/open-folder/open-folder.component.html
webClient/src/app/shared/dialog/open-folder/open-folder.component.ts
webClient/src/app/shared/editor-control/editor-control.service.ts

Fixed slight grammar issues in error messages

Fixed code editor bugs

---

webClient/src/app/shared/editor-control/editor-control.service.ts

Signed-off-by: Jordan Filteau <jfilteau@rocketsoftware.com>

Updated to work with changes to uploading unix files.

---

.gitattributes
webClient/src/app/app.component.scss
webClient/src/app/core/menu-bar/menu-bar.component.scss
webClient/src/app/core/nav/nav.component.scss
webClient/src/app/dashboard/dashboard.component.scss
webClient/src/app/editor/code-editor/code-editor.component.scss
webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.scss
webClient/src/app/editor/code-editor/monaco/monaco.component.scss
webClient/src/app/editor/editor.component.scss
webClient/src/app/editor/frame/frame.component.scss
webClient/src/app/editor/project-tree/project-tree.component.scss
webClient/src/app/shared/dialog/about-project/about-project.component.scss
webClient/src/app/shared/dialog/language-server/language-server.component.scss
webClient/src/app/shared/dialog/new-file/new-file.component.scss
webClient/src/app/shared/dialog/open-folder/open-folder.component.scss
webClient/src/app/shared/dialog/open-project/open-project.component.scss
webClient/src/app/shared/dialog/save-to/save-to.component.scss
webClient/src/app/shared/dialog/tag/tag.component.scss
webClient/src/app/shared/editor-control/editor-control.service.ts
webClient/src/styles/_variables.scss
webClient/src/styles/dialog/_open-project.scss
webClient/src/styles/editor/_editor.scss
webClient/src/styles/editor/_tabs.scss
webClient/src/styles/menu-bar/_menu-bar.scss
webClient/src/styles/nav/_nav.scss
webClient/src/styles/styles.scss

Signed-off-by: Jordan Filteau <jfilteau@rocketsoftware.com>

copyright updates

---

webClient/src/app/app.component.ts
webClient/src/app/editor/code-editor/code-editor.component.html
webClient/src/app/editor/code-editor/code-editor.component.ts
webClient/src/app/editor/code-editor/monaco/monaco.component.ts
webClient/src/app/editor/code-editor/monaco/monaco.service.ts
webClient/src/app/editor/project-tree/project-tree.component.ts
webClient/src/app/shared/editor-control/editor-control.service.ts

Update master to v1.1.0
Signed-off-by: Dmitry Nikolaev dnikolaev@rocketsoftware.com

Update master to v1.1.0

---

webClient/src/app/editor/project-tree/project-tree.component.ts

Mislabeled variable of dir let to thinking b64 file decode was needed when it wasnt

Bugfix for dirs arent files

---

webClient/src/app/core/menu-bar/menu-bar.component.ts

This list shows up in the menu bar, but with the mainframe languages (JCL, ASM) at the bottom due to being unsorted.

Sort language list before display

---

webClient/src/app/editor/code-editor/monaco/monaco.config.ts
webClient/src/app/shared/editor-control/editor-control.service.ts

Language detection was not working well for datasets due to most detection relying on filename extensions.
Broadened JCL detection, but applied across the board changes for dataset language detection by doing pattern matching.
Due to ambiguity of dataset names, this is not a catch-all. Language detection can be improved further by analyzing contents to see which language it is likely to be.

Dataset language detection

---

webClient/src/app/editor/frame/frame.component.html
webClient/src/app/shared/b64-decoder.ts

Removed unneeded header for file explorer. Fixed trailing nulls of b64 decode getting into string output

File content trailing null stripping, File explorer header removal

---

webClient/src/app/editor/code-editor/code-editor.component.ts

selecting first tab on close of selected tab

---

webClient/package-lock.json

updated package-lock by deleting node_modules and package-lock.json and doing an npm install
Signed-off-by: Reet Chowdhary <rchowdhary@rocketsoftware.com>

updating package-lock

---

webClient/src/app/shared/b64-decoder.ts

Signed-off-by: Reet Chowdhary <rchowdhary@rocketsoftware.com>

added license

---

pluginDefinition.json
webClient/src/app/core/menu-bar/menu-bar.component.html
webClient/src/app/core/menu-bar/menu-bar.component.scss
webClient/src/app/core/menu-bar/menu-bar.component.ts
webClient/src/app/core/menu-bar/menu-bar.config.ts
webClient/src/app/shared/editor-control/editor-control.service.ts

- Make default window smaller, for small monitors
- Add ability to disable menu items
- highlighting improvements for dataset name section detection
- add clickable snackbar to open explorer
- Rely on apiml for explorer uri

JCL submission through explorer and apiml, highlight improvements

---

webClient/src/app/app.component.scss
webClient/src/app/core/menu-bar/menu-bar.component.scss
webClient/src/app/editor/frame/frame.component.scss

Changes to the language menu so it does not spill over

ui changes to language menu

---

webClient/package-lock.json
webClient/package.json
webClient/src/app/editor/project-tree/project-tree.component.html
webClient/src/app/editor/project-tree/project-tree.component.ts
webClient/src/app/shared/model/editor-project.ts

Updated file-editor to use file-explorer rather than built-in data set explorer.
Must merge with:
https://github.com/zowe/zlux-file-explorer/pull/23

Data set file explorer

---

webClient/package-lock.json

Signed-off-by: Timothy Gerstel <tgerstel@rocketsoftware.com>

For QA testing only

---

webClient/src/app/editor/code-editor/code-editor.component.html
webClient/src/app/editor/code-editor/code-editor.component.ts
webClient/src/app/editor/code-editor/monaco/monaco.component.html
webClient/src/app/editor/code-editor/monaco/monaco.component.ts

Focus editor by focusing ngx-monaco innner element

---

webClient/src/app/editor/code-editor/code-editor.component.ts

In the event that a window is minimized then restored, focus monaco part of editor.

Small change for focus on restore 

---

webClient/src/app/app.component.ts
webClient/src/app/core/menu-bar/menu-bar.component.ts
webClient/src/app/editor/code-editor/code-editor.component.ts
webClient/src/app/shared/editor-control/editor-control.service.ts

add switch alt+t, close alt+w, and focus on tab

---

webClient/package-lock.json
webClient/package.json
webClient/src/app/app.component.ts
webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.ts
webClient/src/app/editor/project-tree/project-tree.component.html
webClient/src/app/editor/project-tree/project-tree.component.ts
webClient/src/app/shared/editor-control/editor-control.service.ts
webClient/src/app/shared/http/http.data.adapter.service.ts

Allow for app2app to open up a dataset. Also, cleanup of file explorer

---

webClient/package-lock.json
webClient/src/app/app.component.scss
webClient/src/app/shared/snack-bar.service.ts
webClient/src/styles/global.css

Signed-off-by: Suneeth Keerthy <skeerthy@rocketsoftware.com>

Fix the material conflicts between notification manager and zlux-editor

---

webClient/src/app/shared/editor-control/editor-control.service.ts

Signed-off-by: Timothy Gerstel <tgerstel@rocketsoftware.com>

Bug fix: No text in the file has just been created

---

webClient/src/app/editor/code-editor/monaco/monaco.config.ts

Signed-off-by: Yash Jain <ydjainopensource@gmail.com>

Add syntax highlighting support for BPXPRM and IEASYS

---

webClient/package-lock.json

Updated package-lock

---

webClient/package-lock.json
webClient/package.json

Fixing package for properties feature

---

webClient/package-lock.json

Update package-lock for FE

---

webClient/package-lock.json
webClient/package.json
webClient/src/app/editor/code-editor/code-editor.component.html
webClient/src/app/editor/project-tree/project-tree.component.ts

Package-locks for QA

---

webClient/package-lock.json
webClient/package.json

Package-lock to update right click deletion

---

webClient/package-lock.json

Addressed code review changes

---

webClient/src/app/editor/code-editor/code-editor.component.ts

window actions to change Editor title to open file

---

webClient/package-lock.json

Update package-lock to remove long abs path name

---

webClient/src/app/core/menu-bar/menu-bar.config.ts

Signed-off-by: Suneeth Keerthy <skeerthy@rocketsoftware.com>

Removed the delete option from the file menu

---

webClient/package-lock.json
webClient/src/app/core/menu-bar/menu-bar.component.ts

Updated package-lock + accounted for Menu bar edgecase

Updated package-lock + accounted for Menu bar edgecase

---

webClient/package-lock.json

Signed-off-by: Suneeth Keerthy <skeerthy@rocketsoftware.com>

Update to zlux file explorer with dataset deletion

---

webClient/src/app/editor/project-tree/project-tree.component.ts
webClient/src/app/shared/editor-control/editor-control.service.ts

- Enabled read-only mode for GDG, VSAM datasets
- Added commented out TODO in case PDSE do not work

Disabled write support for VSAM, GDG

---

webClient/src/app/editor/code-editor/code-editor.component.html
webClient/src/app/editor/frame/frame.component.html
webClient/src/app/editor/project-tree/project-tree.component.html
webClient/src/index.html

Removing commented out code in zlux editor to clear up SonarQube findings.

Zluxeditor sonarqube cleanup

---

webClient/package-lock.json
webClient/src/app/core/menu-bar/menu-bar.component.ts
webClient/src/app/editor/code-editor/monaco/monaco.service.ts

Fix bug where Material dialogs would overlap on top of login screen
Dialogs exist in the global Material CDK container, which can't be manipulated very easily to hide behind login screen but show up over the Editor. So we dismiss them

Fix bug where Material dialogs would overlap on top of login screen

---

webClient/package-lock.json

Package-lock update for ds search qualifier

---

webClient/src/app/editor/code-editor/code-editor.component.ts

Re-evaluate Editor div after opening file

---

CHANGELOG.md
webClient/package-lock.json
webClient/package.json

Bump file tree version to get pds bugfix

---

CHANGELOG.md
pluginDefinition.json
webClient/src/app/app.component.scss
webClient/webpack.build.config.js

This bug appears to have existed since the monaco refactor.

CSS would not load when using apiml

---

CHANGELOG.md
pluginDefinition.json
webClient/package-lock.json
webClient/package.json
webClient/webpack.build.config.js

Things to test:
1. try editor with a C or JS file, look for fold icons and syntax coloring
2. try editor with/without APIML route, to ensure that the URLs are interpreted correctly. It looks correct to me.

Updated webpack in order to copy missing icons into web folder

---

README.md
webClient/.npmrc
webClient/package-lock.json

no need to explicitly set @zowe config registry.
.npmrc file set the registry location for @zowe namespace.

add .npmrc to set @zowe registry

---

CHANGELOG.md
pluginDefinition.json
webClient/package-lock.json
webClient/package.json
webClient/src/app/editor/editor.module.ts
webClient/src/app/editor/project-tree/project-tree.component.ts

update editor version and file tree version

---

webClient/package-lock.json
webClient/package.json

Update package-lock to include Leonty's changes

---

CHANGELOG.md
pluginDefinition.json
webClient/package.json
webClient/src/app/core/menu-bar/menu-bar.component.ts
webClient/src/app/core/menu-bar/menu-bar.config.ts
webClient/src/app/editor/code-editor/code-editor.component.html
webClient/src/app/editor/code-editor/code-editor.component.ts
webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.html
webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.scss
webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.ts
webClient/src/app/editor/code-editor/monaco/monaco.service.ts

Fairly straightforward
PR 1 of 2
PR 2: https://github.com/zowe/zlux-file-explorer/pull/108

Added option to refresh file content + fix unsaved changes symbol not showing

---

webClient/package-lock.json
webClient/package.json

Updated File Tree in package-lock

---

webClient/src/app/editor/code-editor/code-editor.module.ts
webClient/src/app/editor/code-editor/loading-indicator/loading-indicator.component.html
webClient/src/app/editor/code-editor/loading-indicator/loading-indicator.component.scss
webClient/src/app/editor/code-editor/loading-indicator/loading-indicator.component.ts
webClient/src/app/editor/code-editor/loading-status.ts
webClient/src/app/editor/code-editor/monaco/monaco.component.scss
webClient/src/app/editor/code-editor/monaco/monaco.service.ts

Content load status indicator

---

webClient/src/app/editor/code-editor/monaco/monaco.service.ts

Fix for a bug introduced in previous PR #190 .

Restore correct dataset conversion

---

webClient/src/app/core/menu-bar/menu-bar.config.ts
webClient/src/app/shared/editor-control/editor-control.service.ts

Changed file tab logic to better check false duplicates

---

webClient/package-lock.json
webClient/package.json

Update package to include FT release

---

webClient/package-lock.json
webClient/package.json

Updated FT

---

webClient/package-lock.json
webClient/package.json
webClient/src/app/core/menu-bar/menu-bar.component.ts
webClient/src/app/editor/project-tree/project-tree.component.ts
webClient/src/app/shared/editor-control/editor-control.service.ts

Update package.json w/ File Tree search bar changes (Alt + P)

---

webClient/src/app/app.component.scss
webClient/src/app/editor/code-editor/monaco-settings/monaco-settings.component.html
webClient/src/app/editor/code-editor/monaco-settings/monaco-settings.component.scss
webClient/src/app/editor/code-editor/monaco-settings/monaco-settings.component.ts
webClient/src/app/editor/code-editor/monaco/monaco.component.ts
webClient/src/app/editor/code-editor/monaco/monaco.config.ts
webClient/src/app/shared/editor-control/editor-control.service.ts
webClient/src/styles.scss
webClient/src/styles/global.css

Small change to UI for the settings menu

---

webClient/package-lock.json
webClient/package.json

Very, very important commit

---

webClient/package-lock.json
webClient/package.json

Update FT version 0.8 --> 0.9

---

webClient/src/app/shared/dialog/tag/tag.component.html

disabling the save button- Forcing the user to choose the encoding before saving any file
https://github.com/zowe/zlux/issues/680

disabling the save button- Forcing the user to choose the encoding before saving any file

---

webClient/src/app/app.component.scss
webClient/src/app/shared/dialog/save-to/save-to.component.scss
webClient/src/styles.scss
webClient/src/styles/global.css

changing the selected text font color from white to black, to make it visible when a value is selected from select dropdown
The value was getting selected from the select drop-down, without any issue, however, the selected value was not visible against the white background as the selected text was white. 
Fix: changing the selected text font color from white to black, to make it visible when a value is selected from the select dropdown
https://github.com/zowe/zlux/issues/659

changing the selected text font color from white to black, to make it visible when a value is selected from select dropdown

---

CHANGELOG.md
webClient/package-lock.json
webClient/package.json
webClient/src/app/core/menu-bar/menu-bar.component.ts
webClient/src/app/editor/code-editor/code-editor.component.html
webClient/src/app/editor/code-editor/code-editor.component.ts
webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.ts
webClient/src/app/editor/code-editor/monaco/monaco.component.html
webClient/src/app/editor/code-editor/monaco/monaco.component.ts
webClient/src/app/editor/code-editor/monaco/monaco.service.ts
webClient/src/app/shared/editor-control/editor-control.service.ts

This PR addresses Issue: https://app.zenhub.com/workspaces/web-ui-squad-60549e46bd10bf00115d1f69/issues/zowe/zlux/688
This PR depends upon the following PRs: This PR is a prerequisite to making full-featured DS write support for Editor
To activate, use menu function in the top left. You can also toggle via Ctrl + V and enable via right click Tab -> Compare
Ctrl + S and saving also now works inside the diff navigator left and right-hand sides
Known issues: This doesn't seem to work with multiple Editor windows open.
TODO: There seems to be some resizing/rendering issues when resizing Editor window, Diff viewer does not update. You also see …

Initial prototype for previously selected content comparisons (Diff Viewer)

---

CHANGELOG.md
webClient/package-lock.json
webClient/package.json
webClient/src/app/shared/dialog/delete-file/delete-file.component.html
webClient/src/app/shared/dialog/language-server/language-server.component.html
webClient/src/app/shared/dialog/new-file/new-file.component.html
webClient/src/app/shared/dialog/open-dataset/open-dataset.component.html
webClient/src/app/shared/dialog/open-dataset/open-dataset.component.ts
webClient/src/app/shared/dialog/open-folder/open-folder.component.html
webClient/src/app/shared/dialog/open-project/open-project.component.html
webClient/src/app/shared/dialog/save-to/save-to.component.html
webClient/src/app/shared/dialog/tag/tag.component.html
webClient/src/styles.scss

This PR addresses Issue: https://github.com/zowe/zlux/issues/387
This PR depends upon the following PRs: 

adding the x button on dialogue boxes and removing the cancel button

---

webClient/src/app/shared/dialog/save-to/save-to.component.html
webClient/src/styles.scss

correcting the alignments in save-as dialogue and removing the redundancies 

---

CHANGELOG.md
webClient/src/app/editor/code-editor/monaco/monaco.component.ts

Instructs the editor to remeasure its container when switching from diff viewer to code-editor
Steps to reproduce the issue:
1. open 2 files in a diff viewer
2. now open a new file or open an existing file from File-tree
3. the new file will not render properly in the code-editor
4. now try to change the size of editor window and the issue will be gone

Instructing the editor to remeasure its container when switching from diff viewer to code-editor

---

CHANGELOG.md
webClient/src/app/editor/code-editor/code-editor.component.html
webClient/src/app/editor/code-editor/code-editor.component.ts
webClient/src/app/editor/code-editor/monaco/monaco.component.html
webClient/src/app/editor/code-editor/monaco/monaco.component.scss
webClient/src/app/editor/code-editor/monaco/monaco.component.ts
webClient/src/app/editor/code-editor/monaco/monaco.service.ts
webClient/src/app/shared/dialog/overwrite-dataset/overwrite-dataset.component.html
webClient/src/app/shared/dialog/overwrite-dataset/overwrite-dataset.component.ts
webClient/src/app/shared/editor-control/editor-control.service.ts

This PR addresses Issue: https://jira.rocketsoftware.com/browse/MVD-5070
- For every dataset read operation the e-tag is read from the response body and for every write operation the same e-tag is sent back in request body and in header
- If the e-tag does not match user can choose to compare/overwrite the dataset
- To compare the dataset the diff-viewer is populated with the latest content from the server
- After comparing the dataset user can accept the latest dataset content from the server and the latest e-tag is cached.
- Open the dataset in the editor.
- Modify the same dataset on the Mainframe.
- Update and save the dataset in the editor. In this case the below pop up will be shown.
- On …

Dataset Conflits In Diff-Viewer

---

webClient/src/app/app.component.ts
webClient/src/app/editor/code-editor/monaco/monaco.component.ts
webClient/src/app/editor/code-editor/monaco/monaco.service.ts
webClient/src/app/shared/editor-control/editor-control.service.ts
webClient/src/app/shared/http/http.service.ts

Modification to the angular upgrade

Modification to angular upgrade
