zowe/zlux-editor

- webClient/src/app/shared/editor-control/editor-control.service.ts
I will implement the rest of the API in the File Explorer. I've tested this, and it works without issues for the new API. As a default, I'm forcing the overwrite of currently existing files and encoding them into IBM-1047 (which shouldn't cause any problems as far as I can tell). The option to select encoding will be easier to implement when I can detect the unix file tags in the File Explorer.
> Fixed the API request for PUT

- webClient/src/app/editor/project-tree/project-tree.component.ts
The folder animation seems to be slowing the UI down a fair amount and I believe the expansion looks fine without the animation
> Disabled animation for folder expansion

- webClient/src/app/app.component.ts
- webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.ts
- webClient/src/app/editor/code-editor/monaco/monaco.component.ts
- webClient/src/app/editor/code-editor/monaco/monaco.config.ts
- webClient/src/app/editor/project-tree/project-tree.component.ts
- webClient/src/app/shared/editor-control/editor-control.service.ts
- webClient/src/app/shared/http/http.data.adapter.service.ts
Passing around the zowe named logger to components, directives, and services within the editor. This should hide a bit of debugging info that was spat out before.
> Switched console log to zowe logger

- webClient/src/app/shared/editor-control/editor-control.service.ts
To be merged upon merge of API changes.
> Source & target encoding are sent upon retrieval of sessionid

- webClient/src/app/app.component.ts
- webClient/src/app/editor/code-editor/code-editor.component.html
- webClient/src/app/editor/code-editor/code-editor.component.ts
- webClient/src/app/editor/code-editor/monaco/monaco.component.ts
- webClient/src/app/editor/code-editor/monaco/monaco.service.ts
- webClient/src/app/editor/project-tree/project-tree.component.ts
- webClient/src/app/shared/editor-control/editor-control.service.ts
Implements app2app listener for opening up to a directory, DS listing, or a file.
Fixed a bug along the way too, where a file window would be open but empty due to a timing issue where an exception got thrown. It wasn't subscribing to an event properly.
Also removed the use of the monaco font... it was failing to load, making for an ugly font fallback.
Also disabled unused LSP websocket. Can reenable when we start making use of it.
> app2app to open to files, folders, dslist

- webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.ts
- webClient/src/app/editor/code-editor/monaco/monaco.component.ts
Two elements (tab bar and editor) have functions for being called when parent elements are resized. This makes resizing more correct but it doesn't solve all issues yet.
Somehow, the editor area (as opposed to the file tree area) ends up expanding fine, but not shrinking. Not sure what causes it at this time, but this isnt a regression.
> Resize editor on viewport resize

- webClient/src/app/editor/code-editor/code-editor.component.ts
Implicit values are now more explicit: everything here was true before except that minimap has been turned off due to its use of canvas having a slight performance impact versus how often people use such a thing.
We'll make this end-user configurable soon.
> Small tweak to default configuration for slight performance boost

- webClient/src/app/editor/code-editor/monaco/monaco.service.ts
Added a snackbar that notifies the user if they don't have permissions to open a file or if the file they tried to access no longer exists. Otherwise gives a generic message about not being able to open the file.
Signed-off-by: Reet Chowdhary <rchowdhary@rocketsoftware.com>
> added notifications for failure to open file in editor

- webClient/src/app/core/menu-bar/menu-bar.component.ts
It does not seem like dataset saving is possible currently, so the editor should warn instead of mislead (currently pops up a file saving dialogue instead of a dataset saving one)
> WIP Issue warning on dataset saving

- webClient/package-lock.json
- webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.ts
- webClient/src/app/editor/project-tree/project-tree.component.ts
- webClient/src/app/shared/dialog/delete-file/delete-file.component.html
Bugfix: Now shows default instead of previously display a incorrect (red) themed style.
> git Bugfix/delete incorrect path highlight

- webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.ts
Fix editor file tab behaviour that allows for undesired vertical scrolling
Signed-off-by: Jordan Cain <jordan.cain1@uk.ibm.com>
> Set suppressScrollY to true for perfect scroll file tabs component

- webClient/src/app/core/menu-bar/menu-bar.component.ts
File context for a new file is fetched upon creation and pushed to the initializedFile EventEmitter, fixing the issue where the language menu would not appear.
> [MVD-2967] No language menu for new files

- webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.html
- webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.scss
- webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.ts
- webClient/src/app/editor/frame/frame.component.scss
Previously in Chrome, filenames would wrap onto a new line creating an additional vertical scroll bar in the file tab display.  Additionally, the filename would wrap the close button below the tab which gives the appearance of a missing close button.  Both issues have been mitigated by wrapping the filename within a span and setting a maximum width for the text.  To ensure the scroll bar does not reappear, the bottom margin in the tabs-file-list class has been set to 0px.
Opening many tabs past the current width of the window also created an additional horizontal scroll bar for the body of the app.  This issue has been mitigated by setting a width for the gz-editor class.
> [MVD-2438] Fix for file tab display issues in Chrome

- webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.html
Added tool tip to each tab so that files whose name exceeds the width of the tab may be viewed.
> Tooltips for tabs to display file names that exceed tab width

- webClient/src/app/editor/project-tree/project-tree.component.ts
> made all dataset query to uppercase

- webClient/src/app/core/menu-bar/menu-bar.component.ts
- webClient/src/app/shared/dialog/language-server/language-server.component.ts
- webClient/src/app/shared/language-server/language-server.service.ts
The language server dialog pertains an enable button which was previously unimplemented.  Only the config was saved.  Added functionality to updateSettings() in language-server service.
> Language Server 'enable' toggle not working

- webClient/src/app/editor/code-editor/code-editor.component.ts
- webClient/src/app/editor/code-editor/file-tabs/file-tabs.component.ts
- webClient/src/app/shared/editor-control/editor-control.service.ts
Signed-off-by: aarora4 <lazyc78@gmail.com>
Checked by Michael Roffo
> opening a new file scrolls file bar to the newly opened file

- webClient/src/app/editor/code-editor/code-editor.component.html
- webClient/src/app/editor/code-editor/code-editor.component.ts
- webClient/src/app/editor/code-editor/monaco/monaco.service.ts
- webClient/src/app/shared/editor-control/editor-control.service.ts
Cache and restore cursor and view information per opened file upon selection change
This utilizes monaco's ability to get and set states for the cursor, selection, and view - so we're giving monaco all the info that it expects upon changing the view between multiple files.
Basically, before when selecting tabs in the editor, each tab would get the cursor reset to position 0,0 and any text would be deselected. Now, the position & selection is all preserved while the file remains open. Upon closing the file this information is purged.
> Save and restore cursor and view between tabs

- webClient/src/app/editor/code-editor/monaco/monaco.config.ts
-->
Very tiny fix but this was bothering me an unholy amount.
> Adjusted JCL blue coloring to match ISPF

- webClient/src/app/core/menu-bar/menu-bar.component.scss
Made the menu offset explicit rather than implicit, which had different behavior on webkit versus non webkit browsers.
Webkit: lack of "top" determined that the previous element's height should be the offset
Firefox, edge: lack of "top" meant 0px
> Bugfix for menu positioning

- webClient/src/app/core/menu-bar/menu-bar.component.ts
- webClient/src/app/core/menu-bar/menu-bar.config.ts
- webClient/src/app/editor/code-editor/code-editor.component.ts
- webClient/src/app/editor/code-editor/monaco/monaco.service.ts
- webClient/src/app/editor/project-tree/project-tree.component.ts
- webClient/src/app/shared/editor-control/editor-control.service.ts
- webClient/src/app/shared/message-duration.ts
- Globally increases the shortest duration of snackbar notifications from 2s -> 3s
- Added a "Close All" button in the menu (hotkey is Alt + W + Shift)
- Added a snackbar notification for opening a folder/file you don't have access to
(PR here: https://github.com/zowe/zlux-file-explorer/pull/75)
- Added an "Undo" option to the Close All feature to re-open tabs & files upon accidental missclick
> Added close all + undo setting + hotkey

- CHANGELOG.md
- pluginDefinition.json
- webClient/package-lock.json
- webClient/package.json
- webClient/prune.js
- webClient/webpack.build.config.js
This significantly reduces the package size of the editor by removing assets that are unlikely to be used.
Specifically, .map files (used for development moreso than end-use) and files that have gzip variants (ALL browsers support gzip, so it's not very likely that non-gzip fallback is needed)
> Reduce package size by removing almost certainly unused web assets

- webClient/src/app/app.component.ts
- webClient/src/app/core/menu-bar/menu-bar.component.ts
- webClient/src/app/editor/code-editor/code-editor.component.ts
- webClient/src/app/editor/code-editor/monaco/monaco.service.ts
- webClient/src/app/editor/frame/frame.component.html
- webClient/src/app/editor/frame/frame.component.scss
- webClient/src/app/editor/frame/frame.component.ts
- webClient/src/app/editor/project-tree/project-tree.component.ts
- webClient/src/app/shared/editor-control/editor-control.service.ts
- webClient/src/app/shared/editor-keybinding.service.ts
- Added backwards traversing of the open file tabs, now we have forwards and backwards via Alt + (PAGEUP or **<**) and Alt + (PAGEDOWN or **>**)
- Added & changed some to use keydown, which makes the UX a little more responsive
- When you close a tab, you can undo the close via CTRL + ALT + T
- When you close all tabs, you can undo the whole close via CTRL + ALT + T
- Fixed a bug where if you would close all tabs, then click undo, the Languages menu would disappear
- Changed search to be ALT + P instead of ALT + S (CTRL + ALT + S is often save all/save as), added ALT + B to hide/show the File Tree
> Reviewed keybindings, added some general QoL improvements

- webClient/src/app/editor/frame/frame.component.ts
Alt opens up their settings menu. Chrome handles it well by not opening it if it's a combo w/ another key, but Firefox doesn't
> Stopped event propagation to remove conflict with Firefox

- .gitignore
- CHANGELOG.md
- pluginDefinition.json
- webClient/src/app/core/menu-bar/menu-bar.component.ts
- webClient/src/app/core/menu-bar/menu-bar.config.ts
- webClient/src/app/editor/code-editor/code-editor.component.html
- webClient/src/app/editor/code-editor/code-editor.component.ts
- webClient/src/app/editor/code-editor/code-editor.module.ts
- webClient/src/app/editor/code-editor/monaco-settings/monaco-settings.component.html
- webClient/src/app/editor/code-editor/monaco-settings/monaco-settings.component.scss
- webClient/src/app/editor/code-editor/monaco-settings/monaco-settings.component.spec.ts
- webClient/src/app/editor/code-editor/monaco-settings/monaco-settings.component.ts
- webClient/src/app/editor/code-editor/monaco-settings/monaco-settings.config.ts
- webClient/src/app/editor/code-editor/monaco/monaco.component.ts
- webClient/src/app/editor/code-editor/monaco/monaco.config.ts
- webClient/src/app/editor/code-editor/monaco/monaco.service.ts
- webClient/src/app/shared/editor-control/editor-control.service.ts
- webClient/src/app/shared/model/project-context.ts
- webClient/tsconfig.json
Initial settings menu which allows for customization of builtin monaco features such as the theme, font, and text behavior.
This creates a new menu item "edit" which has the submenu "preferences".
This opens up a tab which is for editing preferences of monaco, and you will see various properties which you can control by input boxes and dropdowns.
There's 3 buttons on this menu: 
* save which saves to the config service (and applies to the editor right away, and the editor uses these settings on startup)
* preview, which takes whatever json is in the text preview area and tries to apply it, if its valid
* reset, which gets the data from the config service again, in case you didnt like your changes.
> Settings menu

- webClient/src/app/editor/code-editor/monaco/monaco.service.ts
- webClient/src/app/shared/editor-control/editor-control.service.ts
When you open a DS currently in dsedit, you will see 4 total calls w/ 1 duplicate. Now you see 3,
and you no longer see "Refreshed successfully" message even when opening DS for the first time
> Removed double datasetContent + setMonacoModel calls

- webClient/src/app/shared/dialog/save-to/save-to.component.html
enable the save button only when fileName, Directory and Encoding have values
The value was getting selected from the select drop-down, without any issue, however, the selected value was not visible against the white background as the selected text was white. 
Fix: changing the selected text font color from white to black, to make it visible when a value is selected from the select dropdown
https://github.com/zowe/zlux/issues/234
> enable the save button only when fileName, Directory and Encoding have values

- CHANGELOG.md
- webClient/src/app/editor/code-editor/monaco/monaco.service.ts
Makes message for when DS cannot be opened (due to undefined length dataset) better + closes the tab instead of leaving a phantom empty tab open
You need access to an undefined length dataset
> Made error handling and UX better for DS not opened case
